onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /simple_vhdl_cpu/in_command_1
add wave -noupdate /simple_vhdl_cpu/in_command_2
add wave -noupdate /simple_vhdl_cpu/in_command_3
add wave -noupdate /simple_vhdl_cpu/in_command_4
add wave -noupdate /simple_vhdl_cpu/in_command_5
add wave -noupdate /simple_vhdl_cpu/in_command_6
add wave -noupdate /simple_vhdl_cpu/ram_addr_1
add wave -noupdate /simple_vhdl_cpu/ram_addr_2
add wave -noupdate /simple_vhdl_cpu/ram_addr_3
add wave -noupdate /simple_vhdl_cpu/ram_addr_4
add wave -noupdate /simple_vhdl_cpu/ram_addr_5
add wave -noupdate /simple_vhdl_cpu/ram_addr_6
add wave -noupdate /simple_vhdl_cpu/clk
add wave -noupdate /simple_vhdl_cpu/value1_1
add wave -noupdate /simple_vhdl_cpu/value2_1
add wave -noupdate /simple_vhdl_cpu/out_operand1_1
add wave -noupdate /simple_vhdl_cpu/out_operand2_1
add wave -noupdate /simple_vhdl_cpu/out_val_1
add wave -noupdate /simple_vhdl_cpu/we_reg_1
add wave -noupdate /simple_vhdl_cpu/flag_idle_1
add wave -noupdate /simple_vhdl_cpu/flag_idle_2
add wave -noupdate /simple_vhdl_cpu/flag_idle_3
add wave -noupdate /simple_vhdl_cpu/flag_idle_4
add wave -noupdate /simple_vhdl_cpu/flag_idle_5
add wave -noupdate /simple_vhdl_cpu/flag_idle_6
add wave -noupdate /simple_vhdl_cpu/ram_val_in_1
add wave -noupdate /simple_vhdl_cpu/ram_val_out_1
add wave -noupdate /simple_vhdl_cpu/we_1
add wave -noupdate /simple_vhdl_cpu/RAM/mem_arr
add wave -noupdate /simple_vhdl_cpu/RAM/we_1
add wave -noupdate /simple_vhdl_cpu/RAM/addr_1
add wave -noupdate /simple_vhdl_cpu/RAM/datai_1
add wave -noupdate /simple_vhdl_cpu/RAM/datao_1
add wave -noupdate /simple_vhdl_cpu/RAM/flag_idle_1
add wave -noupdate /simple_vhdl_cpu/REGS/we_1
add wave -noupdate /simple_vhdl_cpu/REGS/addr1_1
add wave -noupdate /simple_vhdl_cpu/REGS/addr2_1
add wave -noupdate /simple_vhdl_cpu/REGS/datai_1
add wave -noupdate /simple_vhdl_cpu/REGS/datao1_1
add wave -noupdate /simple_vhdl_cpu/REGS/datao2_1
add wave -noupdate /simple_vhdl_cpu/REGS/regs
add wave -noupdate /simple_vhdl_cpu/conveyor_1/counter
add wave -noupdate /simple_vhdl_cpu/conveyor_1/now_command
add wave -noupdate /simple_vhdl_cpu/conveyor_1/now_operand_1
add wave -noupdate /simple_vhdl_cpu/conveyor_1/now_operand_2
add wave -noupdate /simple_vhdl_cpu/conveyor_1/value_operand_1
add wave -noupdate /simple_vhdl_cpu/conveyor_1/value_operand_2
add wave -noupdate /simple_vhdl_cpu/conveyor_1/out_operand_1
add wave -noupdate /simple_vhdl_cpu/conveyor_1/out_operand_2
add wave -noupdate /simple_vhdl_cpu/conveyor_1/out_val
add wave -noupdate /simple_vhdl_cpu/conveyor_1/ram_addr
add wave -noupdate /simple_vhdl_cpu/conveyor_1/ram_val_in
add wave -noupdate /simple_vhdl_cpu/conveyor_1/ram_val_out
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {10000 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 293
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1000
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {10 ns} {50 ns}
